credentials:
  usernames:
    smss:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$qY4hkyw4.LIKmKAqV1paiefNe4NzjnjgTBnGFDklRfwduEVnCXviS
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
    - melsby@gmail.com
