version: '3.9'
volumes:
  postgres-data:
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432
