{
 "title": "worker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum by (job) (process_start_time_seconds) "
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (process_open_fds) "
    }
   ]
  },
  {
   "title": "Worker Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "worker_info{job=\"workers\"}"
    }
   ]
  },
  {
   "title": "Current Task",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "current_task_info{job=\"workers\"}"
    }
   ]
  },
  {
   "title": "Ram Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (process_resident_memory_bytes) "
    }
   ]
  },
  {
   "title": "Current task progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "progress{job=\"workers\"}"
    }
   ]
  },
  {
   "title": "Number of received strategies per symbol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "recived_strategy_total{job=\"workers\"}"
    }
   ]
  },
  {
   "title": "API 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Number of received strategies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(recived_strategy_total{job=\"workers\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum (increase(http_request_size_bytes_sum[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (method, status) (increase(http_requests_total[$__rate_interval]))"
    }
   ]
  }
 ]
}